### ISSUE TITLE
Incorrectly shows "Reported: Did Not Play Selected Role"

### ISSUE THREAD

**Issue by bitvan** [bongikairu/illuminate#11]
So, there are lots of games displayed on
https://steamcommunity.com/my/gcpd/570/?category=Account&tab=MatchPlayerReportIncoming
that says all "No" in all columns.

Somehow, illuminate.dotasphere.com will display all of these as "Reported: Did Not Play Selected Role". But I never even played any ranked games in the past days and is thus impossible to be reported as such. Some of these games are the new Mo'rokai mode, some are turbo normal.

Is this a known bug?

**Comment by bongikairu** [comment]
It's still an issue that need confirmation at #9

**Comment by bongikairu** [comment]
Should no longer be problem as GDPR page is updated
