### ISSUE TITLE
2.0.0 beta is here, need testing

### ISSUE THREAD

**Issue by bongikairu** [bongikairu/illuminate#13]
Hey! 2.0.0 is here

There's many thing in this release. This biggest one is UI rewrite. Report Page is rewritten in react (w/ hook). This should allow people to contribute to UI more easily. Unknown player (whether it's just changed name or non-exposed match data) also get a proper UI instead of prompt.

To try this, change https://illuminate.dotasphere.com/#xxxxxx to https://illuminate.dotasphere.com/index-v2.html#xxxxxx when viewing output

Example

V1
https://illuminate.dotasphere.com/#Kuzon,5037477426-00001111,5035094634-00001111,5033988006-00001111,5033988006-00001111,5029212428-00001111,5029179410-00001111,

V2
https://illuminate.dotasphere.com/index-v2.html#Kuzon,5037477426-00001111,5035094634-00001111,5033988006-00001111,5033988006-00001111,5029212428-00001111,5029179410-00001111,

V2, can't determine player
https://illuminate.dotasphere.com/index-v2.html#KuzonXXXXXXX,5037477426-00001111,5035094634-00001111,5033988006-00001111,5033988006-00001111,5029212428-00001111,5029179410-00001111,

**Comment by bongikairu** [comment]
TODO
- replace whole moment with something smaller but still easy to read
- cache new name to localstorage when choosing in a undetermined player block

**Comment by BrutalBirdie** [comment]
Tested in Chrome and Firefox, both deliver en empty page.
https://illuminate.dotasphere.com/index-v2.html#BrutalBirdie
https://illuminate.dotasphere.com/#BrutalBirdie

**Comment by BrutalBirdie** [comment]
Big Note for other users who want to help testing. Be patient when the script is running, it will take some time (I got fooled by that)

Tested V2 in Chrome and Firefox.
Both working as intended ending in a HUGE page of over 200+ matched parsed.

You are serving http images on a https :)
```
Mixed Content: The page at '<URL>,' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
```

**Comment by tweetyjade** [comment]
instead of asking who you are, is it possible input/pull the steamID and just load from that?

**Comment by bongikairu** [comment]
Yes and no. ID will only be included for player that expose match data. This will still help user that change display name a lot though. Will be working on it.

**Comment by bongikairu** [comment]
BTW, this seems stable enough. Will replace old page with this very soon.

**Comment by bongikairu** [comment]
2.0.0 is live!
