### ISSUE TITLE
Broken firefox/chrome

### ISSUE THREAD

**Issue by mauriciolanda4** [bongikairu/illuminate#14]
When i paste in scratchpad it is showing:

TypeError: h is null
 
When i paste it in the chrome url following javascript: it dissapears.

when i open it on VS Code it is showing that it is not recognizing document.

Is it just me?, i copied it from the website.

P.S.: Sorry for opening a possible duplicate of an issue

**Comment by bongikairu** [comment]
I'm not entirely sure what you mean. Could you try capturing a video?

**Comment by FireCulex** [comment]
Firefox scratch pad

/*
Exception: SyntaxError: unexpected token: identifier
@Scratchpad/1:10
*/

**Comment by bongikairu** [comment]
In scratchpad, after typing allow pasting, you will need to delete that before running script

**Comment by FireCulex** [comment]
That works thank you. Its confusing because the website says type javascript: in the url which in Firefox or Chrome just opens up your search engine. In Firefox you have to use scratchpad and chrome press ctrl-shift-j, it took some googling to figure out how to execute javascript but it appears to work in both browsers. 

Steam third party login...?

**Comment by mauriciolanda4** [comment]
It works for me as well, it was unusual given that before only typing JavaScript: was enough, thank you

**Comment by bongikairu** [comment]
Will it be easier if this is packaged as chrome/firefox extension. Are people more comfortable using that than manually pasting js everytime?

**Comment by mauriciolanda4** [comment]
It would be more helpful for people that want it more ready and accessible, for non tech people

**Comment by mauriciolanda4** [comment]
We could work on that if you want to, I'm interested to be part of/contributor of this application, If yes I could start writing the README, checking code and such.

**Comment by FireCulex** [comment]
I would much prefer an extension and I think it would also be easier to use.

**Comment by bongikairu** [comment]
Continue in #18
