### ISSUE TITLE
Infinite loading on both Chrome and Firefox 

### ISSUE THREAD

**Issue by Valisk** [bongikairu/illuminate#15]
Not entirely sure what the issue is but I haven't been able to use this script for several months now. I enter the script and it correctly brings up my username, but the loading prompt is never-ending and my report/commend information never actually appears.

**Comment by bongikairu** [comment]
try using v2 as described in #13 , see if it solve your problem with no name matched and prompt

**Comment by Valisk** [comment]
This is what I see when I try using the scratchpad in Firefox and the script in Chrome. ![Screenshot_2019-09-25 Illuminate](https://user-images.githubusercontent.com/9488246/65644847-67869200-dfc3-11e9-8ea0-9c71b280459f.png)

When using the https://illuminate.dotasphere.com/index-v2.html# link, I see a blank blue screen.

**Comment by kakarot1998** [comment]
i have the same problem as @Valisk , hope you guys have a solution for this!

**Comment by bongikairu** [comment]
Would you mind posting the full result url? (include everything that came after #). Or send me privately on other channel like reddit (u/bongikairu).

**Comment by kakarot1998** [comment]
@bongikairu i have sent you the url on reddit

**Comment by bongikairu** [comment]
Got it, seem like player name with comma is not encoded properly and causing this problem.

**Comment by kakarot1998** [comment]
gotcha, ill change my name and keep you updated!

**Comment by kakarot1998** [comment]
Update : it works now , but it cant seem to find out which one of the heroes am i

**Comment by bongikairu** [comment]
I assumed your old display name is Blood Fire Death? It's on like every match there.

**Comment by kakarot1998** [comment]
Yes it was

**Comment by bongikairu** [comment]
Click on it and it should be automatically chosen on every other match

**Comment by kakarot1998** [comment]
Done, thank you for the assistance!

**Comment by bongikairu** [comment]
New version of script is up, @Valisk see if this solve your problem

**Comment by Valisk** [comment]
Hey, it worked. I had to use the scratchpad in Firefox but it worked just fine for the first time in months. Nice job, thanks for the update.
