### ISSUE TITLE
its broken since dota update 26.09.2019

### ISSUE THREAD

**Issue by alekskomp** [bongikairu/illuminate#17]
Its broken since this https://twitter.com/wykrhm/status/1177305096259948546 update.
All "Reported: Did Not Play Selected Role" is actualy commends

![image](https://user-images.githubusercontent.com/45537705/65725362-21acf500-e0bb-11e9-965f-d357bc96548b.png)

**Comment by FireCulex** [comment]
Confirmed, the reason is the MatchPlayerReportIncoming added additional columns

**Comment by bongikairu** [comment]
2.0.2 is out and fix this. We don't have to guess about blank report row anymore!
