### ISSUE TITLE
Chrome/Firefox Extension Discussion

### ISSUE THREAD

**Issue by bongikairu** [bongikairu/illuminate#18]
Flow using extension
1. Visit illuminate, or skip straight to 3
2. Click to Install extension if needed
3. Go to gdpr page
4. If the extension is active, there'll be a button to "view result on Illuminate"
5. Script is run, and result is shown on website like current version

**Comment by bongikairu** [comment]
Also, it would be nice if anyone familiar with extension can help me with this

**Comment by mauriciolanda4** [comment]
There is no need to visit illuminate with the extension, it could be to go straight to 3, and we have a link in the bottom to reference the illuminate page, what do you think of a dropdown view?

**Comment by bongikairu** [comment]
I think that no one can remember Steam GDPR url, so we will need an entrance point. It could be a link from illuminate website (website is easy to remember and search), a button on chrome toolbar (personally hide all of them, not even react dev tool and cloudflare is shown), or user manually bookmark it.

**Comment by mauriciolanda4** [comment]
If we give them the GDPR URL they will have the information, we want them to use illuminate, we could redirect to the GDPR URL if illuminate fails (so that they still can see some info), I was thinking of a button that has a dropdown of 2 options, one that is "Login on Steam" and the second that is "view results on illuminate" with a dropdown footer that has the links for the page and the GitHub repo

**Comment by mauriciolanda4** [comment]
Or we could do it as a direct button and if illuminate doesn't respond after some time we send them a Request error message that says "it appears you are not logged in on steam, please make sure you are on your steam account and try again"

**Comment by mauriciolanda4** [comment]
Have you checked if steam has an API for Login verification?, we can do different approachs if it does not have by designing the flow

**Comment by FireCulex** [comment]
They should already have the GDPR URL information, treat it like the netflix extensions? The extension can be greyed out but once you visit the right URL and it senses your logged in it should light up or something then click on it to process. Keep it simple.

**Comment by FireCulex** [comment]
No need for api login info, just see if your on the right URL and it says MatchID and Incoming Match Player Report

**Comment by bongikairu** [comment]
New Flow
1. Visit GDPR Page
2. There'll be a button "view result on Illuminate"
3. result collected and redirected to illuminate to view

If user don't have extension, or forget/not bookmarked GDPR page url
1. Visit Illuminate
2. Install Extension, if need
3. Click on GDPR link

Extension Spec
1. Activated on only Dota 2 MatchReport GDPR Page `https://steamcommunity.com/id/*/gcpd/570?category=Account&tab=MatchPlayerReportIncoming`
2. When activated, inject a button that says "view result on Illuminate"
3. when button is clicked, run current script

**Comment by Steffo99** [comment]
I had the same idea yesterday. Why not make the extension button immediatly take you to the GDPR page?

I was thinking of trying to build a prototype extension... Have you already started work on it?

**Comment by Steffo99** [comment]
I made the prototype!

[Have a look here](https://github.com/Steffo99/chakra-magic/releases) and tell me what do you think! 😄

**Comment by bongikairu** [comment]
Haven't test it, but the code looks good. Maybe signed it and we'll have general audience test it?

**Comment by bongikairu** [comment]
Also, it seems manifest file is kinda the same as chrome. Could it be packed for chrome too?

**Comment by Steffo99** [comment]
Yes, the same code should work on Chrome, but Google requires you to pay a fee for signing...

**Comment by bongikairu** [comment]
Is it $5 ? I can definitely spare that. 

I tried loading from source, it is loaded but JS is not working properly with error like

`Uncaught ReferenceError: exportFunction is not defined`

and

`Uncaught ReferenceError: illuminate is not defined`

A little more push and it should be good for both platform

**Comment by Steffo99** [comment]
[Yup, it's $5.](https://developer.chrome.com/webstore/publish#pay-the-developer-signup-fee)

Appearently, [exportFunction](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.exportFunction) is exclusive to Firefox, so I must find another way to push the `illuminate` function to the web page. 

I'll have a look at it as soon as I get home.

In the meantime, I'm [adding you as a collaborator on the `chakra-magic` project](https://github.com/Steffo99/chakra-magic/invitations), and I'm publishing the extension on https://addons.mozilla.org .

**Comment by Steffo99** [comment]
Addon is awaiting review and will be available at https://addons.mozilla.org/en-US/firefox/addon/chakra-magic/ .

**Comment by bongikairu** [comment]
Chrome extension: https://chrome.google.com/webstore/detail/chakra-magic/ldamnagiplkkoeolomjiigkfaobbecbo

**Comment by bongikairu** [comment]
New instruction ready to deploy when firefox addon is online.

<img width="606" alt="Screenshot 2019-09-30 18 17 35" src="https://user-images.githubusercontent.com/75954/65873941-a8f5b380-e3ae-11e9-8f37-925b0aadb435.png">

**Comment by Steffo99** [comment]
Awesome! I'll alert you when it passes the Mozilla review.

**Comment by bongikairu** [comment]
2.1.0 online, with many code and assets cleanup

**Comment by Steffo99** [comment]
The Firefox extension has been published!

The Mozilla reviewer suggested that I should write a longer description.  
I'll do that before the next release.

**Comment by mauriciolanda4** [comment]
I have this on firefox and chrome extension [in a screenshot](https://i.ibb.co/d6WFkw9/Screen-Shot-2019-10-01-at-11-18-49-AM.png) that may need to be checked.

Apart from that it runs good on both browsers, nice job @Steffo99 :D

**Comment by Steffo99** [comment]
It was ported to Chrome by @bongikairu, I only mantain the Firefox version.

Anyways, thanks! ^^

**Comment by Steffo99** [comment]
(By the way, @bongikairu, can you publish the source code for the Chrome extension?)

**Comment by bongikairu** [comment]
@Steffo99 

It's here awaiting further test

https://github.com/Steffo99/chakra-magic/tree/chrome-test

I will create merge request back into master when it's ready

**Comment by bongikairu** [comment]
@mauriciolanda4 The page is like that without extension though. Valve just added more data without checking the output styling.

**Comment by mauriciolanda4** [comment]
@bongikairu true, just realized that, well, it is a small indie company after all xD

**Comment by Steffo99** [comment]
The PR was merged!

**Comment by mauriciolanda4** [comment]
Do we close this issue?

**Comment by bongikairu** [comment]
For any further issue with extension, please visit https://github.com/Steffo99/chakra-magic
