### ISSUE TITLE
OpenDota not responding - DOMException FireFox

### ISSUE THREAD

**Issue by FireCulex** [bongikairu/illuminate#24]
![firefox_2019-10-05_22-58-25](https://user-images.githubusercontent.com/9983630/66264983-adadd380-e7c3-11e9-8ef1-d95c5951046d.png)

**Comment by Plasticable** [comment]
Same

**Comment by Steffo99** [comment]
I can confirm I'm getting the same problem...

![](https://user-images.githubusercontent.com/1540885/66273140-9fb68c00-e871-11e9-8c4b-d23dcf6e96bd.png)

**Comment by bongikairu** [comment]
Try visiting https://api.opendota.com/api/matches/4907317573 to see if you get cloudflared or not

**Comment by FireCulex** [comment]
It works just fine. https://www.opendota.com/api/matches/5053356025 opens as well despite error. I tried it on Chrome and it works. It may be a Firefox issue.

Ok here we go -

Can't save data for match 5058530620 DOMException: "The quota has been exceeded." script.min.js:109:29

**Comment by bongikairu** [comment]
It's supposed to just skip caching in this case. Will find out why it cause everything to not work after.

**Comment by Steffo99** [comment]
This was fixed in 2.4.0, right? I think you (@bongikairu) can close this.
