### ISSUE TITLE
Cannot read match details

### ISSUE THREAD

**Issue by rek0r** [bongikairu/illuminate#3]
Would read commends but not match details such as kills, deaths, ...
![capture](https://user-images.githubusercontent.com/40262736/41401385-0e29dc48-7003-11e8-82a7-06f87ac03b4d.PNG)

Change the settings to "Expose Public Match Data" would not solve it

**Comment by bongikairu** [comment]
Should be solved in new version. It will now ask which player is you in a match if it can't find a player that match your current name. Could you check again?

**Comment by bongikairu** [comment]
Closing for now

**Comment by rek0r** [comment]
Yes it does ask for the info but that's a bit annoying and inconvenient as I cannot remember which hero I played based on text data of the match. Had to go to dotabuff and confirmed back.
