### ISSUE TITLE
Illuminate says "who are you in this match" a lot

### ISSUE THREAD

**Issue by iancj97** [bongikairu/illuminate#5]
https://i.imgur.com/TdNQeA8.png

If I enter 0, goes away for a little bit until I scroll down.

**Comment by Farewe** [comment]
I have the same issue. It makes the page unusable at the moment because the message pops up indefinitly

**Comment by AveYo** [comment]
Just hack the hack :)
press F12 while on the page to open another Developer Tools and enter in Console tab:
`prompt=function() {return 0}`
skip the 1st prompt by entering 0, then it won't nag again

**Comment by bongikairu** [comment]
See #13 for beta update

**Comment by tweetyjade** [comment]
> See #13 for beta update

checked version 3 too, still prompt popping up nonstop

**Comment by bongikairu** [comment]
If there's still an alert prompt with 0 to skip, you're not using beta version. On new version, It will show a nice list of name and hero right on the match data. It'll still ask on every match if you do not expose your match data though.

**Comment by bongikairu** [comment]
2.0.0 is live, please see if it solve this problem.
