### ISSUE TITLE
Broken for me in Firefox and Chrome

### ISSUE THREAD

**Issue by icheyne** [bongikairu/illuminate#7]
It worked for me a few days ago.

Firefox - nothing happens at all after I paste in Javascript and press enter.

Chrome - returns me to the following URL: 

> https://illuminate.dotasphere.com/#Cheynio,4203085347-00001111,4203085347-00001111,4203085347-00001111,4200209119-00001111,4200209119-00001111,4200032260-00001111,4195373543-00001111,4195373543-00001111,4195373543-00001111,4192251042-00010000,4191317090-00001111,4191317090-00001111,4191070733-00010000,4186574955-00001111,4186574955-00001111,4181973858-00001111,4181973858-00001111,4181973858-00001111,4178576537-00001111,4178576537-00001111,,4178493934-00001111,4175084455-00001111,4173790090-00001111,4173596115-00001111,4173596115-00001111,4173470270-00001111,4173405411-00100000,4170823636-00001111,4170724938-00001111,4170724938-00001111,4170607061-00001111,4170607061-00001111,4170607061-00001111,4170607061-00001111,4169252714-00001111,4165409502-00001111,4165266773-00001111,4164771235-00001111,4164381706-00001111,4164381706-00001111,,4164065582-00001111,4162589310-00001111,4162589310-00001111,4161074543-00001111,4157846755-00001111,4156002320-00000000,4153997111-00001111,4153997111-00001111,4153878383-00001111,4150655935-00001111,4145547123-00001111,4140590116-00001111,4135764168-00100000,4132905575-01010000,4132154457-00001111,4132154457-00001111,4130195076-00001111,4130195076-00001111,4129807108-00001111,4129807108-00001111,,4128353815-00001111,4128353815-00001111,4128353815-00001111,4126846049-00001111,4126846049-00001111,4126715079-00001111,4126715079-00001111,4126715079-00001111,4126715079-00001111,4126508087-01110000,4123717660-01000000,4118180569-00001111,4118135156-00001111,4118135156-00001111,4118135156-00001111,4114723797-00001111,4113569203-00001111,4113096644-00001111,4111516153-00001111,4111516153-00001111,,4109637884-00001111,4109637884-00001111,4108530395-00001111,4108530395-00001111,4107691566-00001111,4107556069-00001111,4106757141-00001111,4106757141-00001111,4106596362-00001111,4077023449-00001111,4077023449-00001111,4074481609-00001111,4074462464-00001111,4070581566-00100000,4070581566-01100000,4057238356-00001111,4057127479-00001111,4055307774-00001111,4055137580-00001111,4054840898-00001111,,4054067462-00001111,4053470502-00001111,4051646087-00001111,4044783385-01110000,4044592877-00001111,4037486387-00001111,4035369795-00010000,4033627911-00001111,4033627911-00001111,4033627911-00001111,4020833261-00001111,4019495787-00001111,4019495787-00001111,4019495787-00001111,4019245263-00010000,4018341943-00001111,4018341943-00001111,4017640854-00001111,3992974521-00001111,3992834580-00110000,,3983900631-00001111,3983900631-00001111,3982265965-00001111,3980745785-00001111,3975317415-00001111,3964085884-00100000,3960662552-00001111,3958750754-00010000,3954784229-00001111,3954759932-00001111,3944747649-00001111,3944747649-00001111,3944747649-00001111,3935994725-00001111,3933933111-00001111,3933490539-00010000,3930787809-00001111,3925688138-00001111,3920168317-00001111,3917404865-00001111,,3915914222-00001111,3913990945-00001111,3912015717-00001111,3912015717-00001111,3912015717-00001111,3910049153-00001111,3904232961-00001111,3904040984-00001111,3903332750-00001111,3902681435-00001111,3901377084-00001111,3899222218-00001111,3899222218-00001111,3897132918-00001111,3897132918-00001111,3883330865-00001111,3883330865-00001111,3882425552-00001111,3882425552-00001111,3878392688-00001111,,3877942535-00001111,3877942535-00001111,3869603946-00001111,3868624928-00001111,3868624928-00001111,3866573597-00001111,3866520242-00001111,3859289516-00001111,3856052831-00001111,3841097668-00100000,3831313906-00001111,3830957592-00001111,3829581716-00001111,3727882331-00001111,3666921175-01110000,3660732369-00100000,3660732369-00010000,3657186742-00001111,3657186742-00001111,3652132682-00001111,,3636632889-00001111,3631296609-00001111,3631083636-00010000,3631083636-00001111,3627121820-00001111,3625327363-00001111,3625327363-00001111,3625216953-00001111,3616544634-00001111,3615746146-00100000,3615746146-00001111,3615432751-01110000,3614911226-00001111,3614911226-00001111,3609518166-00001111,3591671279-00001111,3586350978-01110000,3582492495-00001111,3580676035-01000000,3580676035-01000000,,3452362003-00001111,3444185785-00001111,3444185785-00001111,3442326412-00001111,3442326412-00001111,

**Comment by bongikairu** [comment]
Firefox might to block `javascript:`, so for now, use it's console while I figured out alternate way to easily use the script

1. Shift + F4 to open scratchpad
2. Paste the script
3. Ctrl + R to run the script, you can close scratchpad while it's running

**Comment by icheyne** [comment]
Thank you. That works.

How about a bookmarklet, userscript or an extension?

**Comment by icheyne** [comment]
In Firefox I manually created a bookmarklet and it worked fine.

**Comment by bongikairu** [comment]
Firefox instruction in future version as in #16 roadmap
