### ISSUE TITLE
It shows empty report message

### ISSUE THREAD

**Issue by althaj** [bongikairu/illuminate#9]
It shows empty report message / type (<td class="summary"></td>) on a certain match. I think it is due to the new report option (wrong role in Ranked Roles) not being implemented in the GDPR page yet.

I think we should not display the entry if there is "no reports" in the GDPR page.

**Comment by bongikairu** [comment]
Can we safely assume that if all row are not "Yes", then it's a report for Ranked Role Wrong Role reports?

**Comment by althaj** [comment]
I don't think there is any other explanation right now. The problem is tho once you have other reports (Intentional feeding for example), you can't be sure if you got reported for wrong role.

**Comment by bongikairu** [comment]
Treating blank report row as Wrong Role now, it should show even when there's another report for the same game. Gonna keep this open issue until verified or busted.

**Comment by camperofcamper** [comment]
![image](https://user-images.githubusercontent.com/2990093/59243664-cb09d100-8c19-11e9-993f-4cffd8b6dcff.png)
¯\_(ツ)_/¯

**Comment by althaj** [comment]
They changed the reports again... I think Valve used the same report for the new block feature. @bongikairu can you just rename it to something like "Blocked by other player"?

**Comment by bongikairu** [comment]
Got it

**Comment by bongikairu** [comment]
#10 

Should we check the timestamp so old report remain the same while new one (after battlepass) shows blocked?

**Comment by althaj** [comment]
Sounds like a good idea! The feature was released with the battle pass on 07 May 2019.

**Comment by camperofcamper** [comment]
Pretty sure you can still report people for not playing their role in ranked match

**Comment by althaj** [comment]
> Pretty sure you can still report people for not playing their role in ranked match

You can't. They changed the report player screen and the button for wrong role is not there anymore.

**Comment by camperofcamper** [comment]
I don't play this mode but recently it received an update.
https://www.reddit.com/r/DotA2/comments/bx837v/dota_2_update_main_client_june_5_2019/

**Comment by bongikairu** [comment]
Need confirmation on this, meanwhile the patch above is live

**Comment by althaj** [comment]
> I don't play this mode but recently it received an update.

Okay I didn't notice this update. What we can do now is this: if the game mode is Ranked Roles (All pick ranked) - give the role report, otherwise give the block one.

**Comment by bongikairu** [comment]
Report will always show something now. If it's still incorrect, file it in #11.
